[build]
  publish = "dist"
  command = "npm run generate"
  functions = "lambda"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200