site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/assets/images/
public_folder: /assets/images/

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'blog'
    label: 'Blog'
    # identifier_field: name
    folder: 'content/blog'
    create: true
    format: 'markdown'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
